version: '3.7'
services: 

  backend:
    container_name: backend-container
    build:
      context: ./backend
    ports:
      - "5000:5000"


  frontend:
    container_name: frontend-container
    build: 
      context: ./frontend
    ports:
      - "3000:3000"      
    volumes: 
      - '.:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    depends_on:
      - backend

