version: '3.7'
services: 

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
    ports:
      - "5000:5000"
    image:
      server-image


  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"        
    volumes: 
      - '.:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    depends_on:
      - backend

