apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bingo-frontend
  name: bingo-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bingo-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bingo-frontend
    spec:
      containers:
      - image: gcr.io/bingodis/bingo-frontend:v1
        name: frontend
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 3000
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: bingo-frontend
  labels:
    run: bingo-frontend
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: bingo-frontend
  type: LoadBalancer